### ISSUE TITLE
Is there a reason for --force-yes when using apt-get install?

### ISSUE THREAD

**Issue by marcoamorales** [escapestudios-cookbooks/hollandbackup#5]
Looking over the recipe that installs `holland-mysqldump` I noticed that you guys are using the `--force-yes` option. Is there a specific reason why this is done? I just tried installing `holland-myslqdump` on Debian 7, 12.04 & 14.04 with just `apt-get install holland-mysqldump -y` and it worked without a problem.

https://github.com/escapestudios-cookbooks/hollandbackup/blob/9689f4fb74c63328e2bf62bf2fea30b47d8e4612/recipes/mysqldump.rb#L11-L14

I'm wondering if there's a reason to use that option, especially since it's considered to be a dangerous option:
```
--force-yes
    Force yes. This is a dangerous option that will cause apt-get to continue without prompting if it is doing something potentially harmful. It should not be used except in very special situations. Using --force-yes can potentially destroy your system! 
```

**Comment by djoos** [comment]
Hi @marcoamorales,

thanks for getting in touch - we had a look into the --force-yes and are not 100% where that came from. After reading through the docs, we decided to take it out as it should only be used in very special situations...

The commit and release is on its way!

Kind regards,
David

**Comment by marcoamorales** [comment]
Thank you very much! :+1:
